sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t protenhan/rpi-ddclient:build .
# test image
- docker run --entrypoint /bin/ash protenhan/rpi-ddclient:build -c "cat /etc/ddclient/ddclient.conf"
after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
    docker tag protenhan/rpi-ddclient:build netzfisch/rpi-dyndns:$TAG
    docker tag protenhan/rpi-ddclient:build netzfisch/rpi-dyndns:latest
    docker push protenhan/rpi-ddclient:$TAG
    docker push protenhan/rpi-ddclient:latest
  fi
